In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
import pandas as pd

student_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_knowledge_base.csv"

student_df = pd.read_csv(student_path)

print(student_df.shape)
print(student_df.columns.tolist())
print(student_df.head())

(3600, 24)
['Sr_No', 'Job_Profession', 'Student', 'Linguistic', 'Musical', 'Bodily', 'Logical_Mathematical', 'Spatial_Visualization', 'Interpersonal', 'Intrapersonal', 'Naturalist', 'Student_ID', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'Dominant_Intelligence', 'Average_Intelligence_Score', 'Average_Performance', 'Performance_Category']
   Sr_No             Job_Profession Student  Linguistic  Musical  Bodily  \
0      1  Machine Learning Engineer      S1          11        5      12
1      1  Machine Learning Engineer      S2          12        6      12
2      1  Machine Learning Engineer      S3          13        7      12
3      1  Machine Learning Engineer      S4          14        8      12
4      1  Machine Learning Engineer      S5          13        9      12

   Logical_Mathematical  Spatial_Visualization  Interpersonal  Intrapersonal  \
0                    16                     17             11             18
1                    16                     16             11             18
2                    16                     15             11             18
3                    16                     19             11             18
4                    16                     20             11             19

   ...   P3    P4    P5   P6    P7    P8  Dominant_Intelligence  \
0  ...  AVG  BEST  BEST  AVG  BEST  BEST             Naturalist
1  ...  AVG  BEST  BEST  AVG  BEST  BEST             Naturalist
2  ...  AVG  BEST  BEST  AVG  BEST  BEST             Naturalist
3  ...  AVG  BEST  BEST  AVG  BEST  BEST  Spatial_Visualization
4  ...  AVG  BEST  BEST  AVG  BEST  BEST  Spatial_Visualization

  Average_Intelligence_Score Average_Performance Performance_Category
0                      13.62                2.38            Excellent
1                      13.75                2.38            Excellent
2                      13.88                2.38            Excellent
3                      14.62                2.38            Excellent
4                      14.88                2.38            Excellent

[5 rows x 24 columns]

In [5]:
career_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_knowledge_base.csv"

career_df = pd.read_csv(career_path)

print(career_df.shape)
print(career_df.columns.tolist())
print(career_df.head())

(3600, 24)
['Sr_No', 'Job_Profession', 'Student', 'Linguistic', 'Musical', 'Bodily', 'Logical_Mathematical', 'Spatial_Visualization', 'Interpersonal', 'Intrapersonal', 'Naturalist', 'Student_ID', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'Dominant_Intelligence', 'Average_Intelligence_Score', 'Average_Performance', 'Performance_Category']
   Sr_No             Job_Profession Student  Linguistic  Musical  Bodily  \
0      1  Machine Learning Engineer      S1          11        5      12
1      1  Machine Learning Engineer      S2          12        6      12
2      1  Machine Learning Engineer      S3          13        7      12
3      1  Machine Learning Engineer      S4          14        8      12
4      1  Machine Learning Engineer      S5          13        9      12

   Logical_Mathematical  Spatial_Visualization  Interpersonal  Intrapersonal  \
0                    16                     17             11             18
1                    16                     16             11             18
2                    16                     15             11             18
3                    16                     19             11             18
4                    16                     20             11             19

   ...   P3    P4    P5   P6    P7    P8  Dominant_Intelligence  \
0  ...  AVG  BEST  BEST  AVG  BEST  BEST             Naturalist
1  ...  AVG  BEST  BEST  AVG  BEST  BEST             Naturalist
2  ...  AVG  BEST  BEST  AVG  BEST  BEST             Naturalist
3  ...  AVG  BEST  BEST  AVG  BEST  BEST  Spatial_Visualization
4  ...  AVG  BEST  BEST  AVG  BEST  BEST  Spatial_Visualization

  Average_Intelligence_Score Average_Performance Performance_Category
0                      13.62                2.38            Excellent
1                      13.75                2.38            Excellent
2                      13.88                2.38            Excellent
3                      14.62                2.38            Excellent
4                      14.88                2.38            Excellent

[5 rows x 24 columns]

In [6]:
career_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_knowledge_base.csv"

career_df = pd.read_csv(career_path)

print(career_df.shape)
print(career_df.columns.tolist())
print(career_df.head())

(9147, 7)
['category', 'job_title', 'job_description', 'skills', 'num_skills', 'description_length', 'posting_count']
               category                                          job_title  \
0  Business Development  100% Remote | Business Development Manager - B...
1  Business Development  Account Executive, New Business Development, H...
2  Business Development                 Area Director Business Development
3  Business Development          Associate, Corporate Business Development
4  Business Development                               Business Development

                                     job_description  \
0  JOIN THE LEOSOLVE GROUP AND DRIVE GLOBAL BUSIN...
1  ACCOUNT EXECUTIVE, NEW BUSINESS DEVELOPMENT, H...
2  SUNRISE SENIOR LIVING WAS AGAIN CERTIFIED AS A...
3  COMPANY DESCRIPTION AT SERVICENOW, OUR TECHNOL...
4  QUANTUM PAIN AND ORTHOPEDICS IS A PREMIER OUTP...

                                              skills  num_skills  \
0  ['B2B Sales', 'Negotiation', 'Communication', ...          10
1  ['Sales Performance Tracking', 'Presentation S...          19
2  ['Business Development', 'Account Management',...          20
3  ['Market Research', 'Analytical Skills', 'Nego...          16
4  ['Microsoft Office Suite', 'Marketing', 'Data ...          14

   description_length  posting_count
0                2213              1
1                3421              1
2                8957              1
3                7501              1
4                3092              1

In [7]:
employment_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_knowledge_base.csv"

employment_df = pd.read_csv(employment_path)

print(employment_df.shape)
print(employment_df.columns.tolist())
print(employment_df.head())

(9147, 7)
['category', 'job_title', 'job_description', 'skills', 'num_skills', 'description_length', 'posting_count']
               category                                          job_title  \
0  Business Development  100% Remote | Business Development Manager - B...
1  Business Development  Account Executive, New Business Development, H...
2  Business Development                 Area Director Business Development
3  Business Development          Associate, Corporate Business Development
4  Business Development                               Business Development

                                     job_description  \
0  JOIN THE LEOSOLVE GROUP AND DRIVE GLOBAL BUSIN...
1  ACCOUNT EXECUTIVE, NEW BUSINESS DEVELOPMENT, H...
2  SUNRISE SENIOR LIVING WAS AGAIN CERTIFIED AS A...
3  COMPANY DESCRIPTION AT SERVICENOW, OUR TECHNOL...
4  QUANTUM PAIN AND ORTHOPEDICS IS A PREMIER OUTP...

                                              skills  num_skills  \
0  ['B2B Sales', 'Negotiation', 'Communication', ...          10
1  ['Sales Performance Tracking', 'Presentation S...          19
2  ['Business Development', 'Account Management',...          20
3  ['Market Research', 'Analytical Skills', 'Nego...          16
4  ['Microsoft Office Suite', 'Marketing', 'Data ...          14

   description_length  posting_count
0                2213              1
1                3421              1
2                8957              1
3                7501              1
4                3092              1

In [8]:
employment_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/course_knowledge_base.csv"

employment_df = pd.read_csv(employment_path)

print(employment_df.shape)
print(employment_df.columns.tolist())
print(employment_df.head())

(604, 6)
['course_id', 'name', 'institution', 'average_rating', 'review_count', 'knowledge']
                              course_id  \
0                  aboriginal-education
1                   access-control-sscp
2                  accounting-analytics
3      accounting-data-analytics-python
4  actualizacion-manejo-diabetes-tipo-2

                                                name  \
0                aboriginal worldviews and education
1                                    access controls
2                               accounting analytics
3              accounting data analytics with python
4  actualización en el manejo del paciente con di...

                                  institution  average_rating  review_count  \
0                       university of toronto        4.545455            66
1                                      (isc)²        4.294118            34
2                  university of pennsylvania        4.354916           417
3  university of illinois at urbana-champaign        3.285714             7
4     universidad nacional autónoma de méxico        4.825112           223

                                           knowledge
0  Course Name: aboriginal worldviews and educati...
1  Course Name: access controls. Institution: (is...
2  Course Name: accounting analytics. Institution...
3  Course Name: accounting data analytics with py...
4  Course Name: actualización en el manejo del pa...

In [9]:
core_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/core_knowledge_preprocessed.csv"

core_df = pd.read_csv(core_path)

print(core_df.shape)
print(core_df.columns.tolist())
print(core_df.head())

(1167, 4)
['category', 'job_title', 'job_description', 'job_skill_set']
  category                               job_title  \
0       hr            sr human resource generalist
1       hr                 human resources manager
2       hr             director of human resources
3       hr           chief human resources officer
4       hr  human resources generalist hybrid role

                                     job_description  \
0  summarythe sr hr generalist provides hr expert...
1  be part of a stellar team at ysb as the manage...
2  our client is a thriving organization offering...
3  job title chief human resources officer chroin...
4  description who we are avispl is a digital ena...

                                       job_skill_set
0  employee relations, talent acquisition, perfor...
1  talent acquisition, employee performance manag...
2  human resources management, recruitment, emplo...
3  talent management, organizational development,...
4  microsoft office, data analysis, employee onbo...

In [10]:
student_df["text"] = (
    "Job Profession: " + student_df["Job_Profession"].astype(str) +
    "\nDominant Intelligence: " + student_df["Dominant_Intelligence"].astype(str) +
    "\nAverage Intelligence Score: " + student_df["Average_Intelligence_Score"].astype(str) +
    "\nAverage Performance: " + student_df["Average_Performance"].astype(str) +
    "\nPerformance Category: " + student_df["Performance_Category"].astype(str)
)

print(student_df["text"].head(2).to_string(index=False))

Job Profession: Machine Learning Engineer\nDomi...
Job Profession: Machine Learning Engineer\nDomi...

In [11]:
career_df["text"] = (
    "Category: " + career_df["category"].astype(str) +
    "\nJob Title: " + career_df["job_title"].astype(str) +
    "\nJob Description: " + career_df["job_description"].astype(str) +
    "\nSkills: " + career_df["skills"].astype(str)
)

print(career_df["text"].head(2).to_string(index=False))

Category: Business Development\nJob Title: 100%...
Category: Business Development\nJob Title: Acco...

In [12]:
employment_df["text"] = (
    "Course Name: " + employment_df["name"].astype(str) +
    "\nInstitution: " + employment_df["institution"].astype(str) +
    "\nRating: " + employment_df["average_rating"].astype(str) +
    "\nReviews: " + employment_df["review_count"].astype(str) +
    "\nKnowledge: " + employment_df["knowledge"].astype(str)
)

print(employment_df["text"].head(2).to_string(index=False))

Course Name: aboriginal worldviews and educatio...
Course Name: access controls\nInstitution: (isc...

In [13]:
core_df["text"] = (
    "Category: " + core_df["category"].astype(str) +
    "\nJob Title: " + core_df["job_title"].astype(str) +
    "\nJob Description: " + core_df["job_description"].astype(str) +
    "\nSkills: " + core_df["job_skill_set"].astype(str)
)

print(core_df["text"].head(2).to_string(index=False))

Category: hr\nJob Title: sr human resource gene...
Category: hr\nJob Title: human resources manage...

In [14]:
all_documents = pd.concat(
    [
        student_df[["text"]],
        career_df[["text"]],
        employment_df[["text"]],
        core_df[["text"]]
    ],
    ignore_index=True
)

print("Total documents:", len(all_documents))
print(all_documents.head(3))

Total documents: 14518
                                                text
0  Job Profession: Machine Learning Engineer\nDom...
1  Job Profession: Machine Learning Engineer\nDom...
2  Job Profession: Machine Learning Engineer\nDom...

In [15]:
!pip install -q langchain-text-splitters

In [16]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = text_splitter.create_documents(
    all_documents["text"].tolist()
)

print("Total chunks:", len(chunks))
print("\nFirst chunk:")
print(chunks[0].page_content)

Total chunks: 115253

First chunk:
Job Profession: Machine Learning Engineer
Dominant Intelligence: Naturalist
Average Intelligence Score: 13.62
Average Performance: 2.38
Performance Category: Excellent

In [38]:
import os

knowledge_files = [
    "cloud.txt",
    "data_science.txt",
    "deep_learning.txt",
    "generative_ai.txt",
    "machine_learning.txt",
    "python.txt",
    "web_development.txt"
]

for file in knowledge_files:
    path = f"/content/{file}"
    print(file, "->", os.path.exists(path))

cloud.txt -> True
data_science.txt -> True
deep_learning.txt -> True
generative_ai.txt -> True
machine_learning.txt -> True
python.txt -> True
web_development.txt -> True

In [39]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

all_documents = []

for filename in knowledge_files:
    with open(f"/content/{filename}", "r", encoding="utf-8") as f:
        text = f.read()

    all_documents.append({
        "source": filename,
        "text": text
    })

print("Knowledge documents loaded:", len(all_documents))

Knowledge documents loaded: 7

In [37]:
import os

print("Searching for the original RAG .txt files...\n")

search_locations = [
    "/content",
    "/content/drive/MyDrive"
]

target_files = {
    "cloud.txt",
    "data_science.txt",
    "deep_learning.txt",
    "generative_ai.txt",
    "machine_learning.txt",
    "python.txt",
    "web_development.txt"
}

found_files = []

for location in search_locations:
    for root, dirs, files in os.walk(location):
        for file in files:
            if file.lower() in target_files:
                path = os.path.join(root, file)
                found_files.append(path)

print("Found files:", len(found_files))

for path in found_files:
    print(path)

Searching for the original RAG .txt files...

Found files: 0

In [40]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = []

for document in all_documents:
    split_docs = text_splitter.create_documents([document["text"]])

    for doc in split_docs:
        chunks.append({
            "content": doc.page_content,
            "source": document["source"]
        })

print("Total chunks:", len(chunks))
print("\nFirst chunk:")
print(chunks[0]["content"])

Total chunks: 41

First chunk:
CLOUD COMPUTING LEARNING GUIDE

Cloud Computing is the delivery of computing resources such as
servers, storage, databases, networking and software over the
internet.

PREREQUISITES:

Basic computer networking and operating system concepts are
helpful. Basic programming knowledge is also useful.

IMPORTANT TOPICS:

In [41]:
from sentence_transformers import SentenceTransformer
import numpy as np

# Load embedding model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# Extract text from the 41 chunks
knowledge_texts = [chunk["content"] for chunk in chunks]

# Generate embeddings
knowledge_embeddings = embedding_model.encode(
    knowledge_texts,
    convert_to_numpy=True
)

print("Number of embeddings:", knowledge_embeddings.shape[0])
print("Embedding dimension:", knowledge_embeddings.shape[1])

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Number of embeddings: 41
Embedding dimension: 384

In [42]:
import faiss
import numpy as np

# Convert embeddings to float32
embedding_array = np.asarray(
    knowledge_embeddings,
    dtype="float32"
)

# Create FAISS index
index = faiss.IndexFlatL2(
    embedding_array.shape[1]
)

# Add embeddings
index.add(embedding_array)

print("FAISS index created successfully!")
print("Total vectors:", index.ntotal)
print("Vector dimension:", index.d)

FAISS index created successfully!
Total vectors: 41
Vector dimension: 384

In [43]:
import pickle
import faiss

# Save FAISS index
faiss.write_index(index, "/content/faiss_index.index")

# Save knowledge chunks
with open("/content/knowledge_chunks.pkl", "wb") as f:
    pickle.dump(chunks, f)

print("FAISS index saved successfully!")
print("Knowledge chunks saved successfully!")
print("Total chunks saved:", len(chunks))

FAISS index saved successfully!
Knowledge chunks saved successfully!
Total chunks saved: 41

In [44]:
import os

print("Files:")
print(os.path.exists("/content/faiss_index.index"))
print(os.path.exists("/content/knowledge_chunks.pkl"))

Files:
True
True

In [17]:
!pip install -q sentence-transformers

In [18]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded successfully")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model loaded successfully

In [19]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2",
    device="cuda"
)

print("Embedding model loaded successfully")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding model loaded successfully

In [20]:
texts = [chunk.page_content for chunk in chunks]

embeddings = embedding_model.encode(
    texts,
    batch_size=128,
    show_progress_bar=True,
    device="cuda"
)

print("Embedding shape:", embeddings.shape)

Batches:   0%|          | 0/901 [00:00<?, ?it/s]

Embedding shape: (115253, 384)

In [21]:
!pip install -q faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 79.7 MB/s eta 0:00:00

In [22]:
import faiss
import numpy as np

embedding_matrix = np.asarray(embeddings).astype("float32")

index = faiss.IndexFlatL2(embedding_matrix.shape[1])
index.add(embedding_matrix)

print("FAISS index created successfully")
print("Number of vectors:", index.ntotal)
print("Vector dimension:", index.d)

FAISS index created successfully
Number of vectors: 115253
Vector dimension: 384

In [23]:
import os
import pickle

rag_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/RAG"

os.makedirs(rag_path, exist_ok=True)

# Save FAISS index
faiss.write_index(
    index,
    os.path.join(rag_path, "knowledge_base.index")
)

# Save chunks
with open(os.path.join(rag_path, "knowledge_chunks.pkl"), "wb") as f:
    pickle.dump(chunks, f)

print("RAG knowledge base saved successfully!")
print("Files saved:")
print("- knowledge_base.index")
print("- knowledge_chunks.pkl")

RAG knowledge base saved successfully!
Files saved:
- knowledge_base.index
- knowledge_chunks.pkl

In [24]:
import os

knowledge_path = "."

documents = []

for filename in os.listdir(knowledge_path):
    if filename.endswith(".txt"):
        file_path = os.path.join(knowledge_path, filename)

        with open(file_path, "r", encoding="utf-8") as file:
            content = file.read()

        documents.append({
            "filename": filename,
            "content": content
        })

print("Total documents:", len(documents))

for doc in documents:
    print("\nFile:", doc["filename"])
    print("Characters:", len(doc["content"]))

Total documents: 0

In [25]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = []

for doc in documents:
    doc_chunks = text_splitter.split_text(doc["content"])

    for chunk in doc_chunks:
        chunks.append({
            "filename": doc["filename"],
            "content": chunk
        })

print("Total chunks:", len(chunks))

Total chunks: 0

In [31]:
import os

print("Knowledge-base files found:")

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.endswith((".txt", ".json", ".csv")):
            print(os.path.join(root, file))

Knowledge-base files found:
/content/.config/.last_update_check.json
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/all_job_post[1].csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_dataset_cleaned.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_dataset_feature_engineered.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/skill_vocabulary.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_skill_mapping.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_profiles.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_profiles.json
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/category_career_mapping.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/category_career_mapping.json
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/skill_frequency.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_statistics.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_knowledge_base.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_knowledge_base.json
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/course_knowledge_base.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/core_knowledge_preprocessed.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/all_job_post.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_dataset_cleaned.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_statistics.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_intelligence_profiles.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_profiles.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_profiles.json
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_dataset_feature_engineered.csv
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_knowledge_base.json
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_knowledge_base.csv
/content/sample_data/anscombe.json
/content/sample_data/mnist_test.csv
/content/sample_data/mnist_train_small.csv
/content/sample_data/california_housing_test.csv
/content/sample_data/california_housing_train.csv

In [32]:
import pandas as pd
import os

base = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed"

for filename in [
    "career_knowledge_base.csv",
    "course_knowledge_base.csv",
    "core_knowledge_preprocessed.csv"
]:
    path = os.path.join(base, filename)

    df = pd.read_csv(path)

    print("\n" + "="*60)
    print(filename)
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    print("\nFirst 3 rows:")
    display(df.head(3))

============================================================
career_knowledge_base.csv
Shape: (9147, 7)
Columns: ['category', 'job_title', 'job_description', 'skills', 'num_skills', 'description_length', 'posting_count']

First 3 rows:

,category,job_title,job_description,skills,num_skills,description_length,posting_count
0,Business Development,100% Remote | Business Development Manager - B...,JOIN THE LEOSOLVE GROUP AND DRIVE GLOBAL BUSIN...,"['B2B Sales', 'Negotiation', 'Communication', ...",10,2213,1
1,Business Development,"Account Executive, New Business Development, H...","ACCOUNT EXECUTIVE, NEW BUSINESS DEVELOPMENT, H...","['Sales Performance Tracking', 'Presentation S...",19,3421,1
2,Business Development,Area Director Business Development,SUNRISE SENIOR LIVING WAS AGAIN CERTIFIED AS A...,"['Business Development', 'Account Management',...",20,8957,1

============================================================
course_knowledge_base.csv
Shape: (604, 6)
Columns: ['course_id', 'name', 'institution', 'average_rating', 'review_count', 'knowledge']

First 3 rows:

,course_id,name,institution,average_rating,review_count,knowledge
0,aboriginal-education,aboriginal worldviews and education,university of toronto,4.545455,66,Course Name: aboriginal worldviews and educati...
1,access-control-sscp,access controls,(isc)²,4.294118,34,Course Name: access controls. Institution: (is...
2,accounting-analytics,accounting analytics,university of pennsylvania,4.354916,417,Course Name: accounting analytics. Institution...

============================================================
core_knowledge_preprocessed.csv
Shape: (1167, 4)
Columns: ['category', 'job_title', 'job_description', 'job_skill_set']

First 3 rows:

,category,job_title,job_description,job_skill_set
0,hr,sr human resource generalist,summarythe sr hr generalist provides hr expert...,"employee relations, talent acquisition, perfor..."
1,hr,human resources manager,be part of a stellar team at ysb as the manage...,"talent acquisition, employee performance manag..."
2,hr,director of human resources,our client is a thriving organization offering...,"human resources management, recruitment, emplo..."

In [33]:
import pandas as pd
import os

base = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed"

for filename in [
    "career_knowledge_base.csv",
    "course_knowledge_base.csv",
    "core_knowledge_preprocessed.csv"
]:
    path = os.path.join(base, filename)
    df = pd.read_csv(path)

    print("\n" + "="*70)
    print(filename)

    # Search for learning-guide related content
    for col in df.select_dtypes(include="object").columns:
        matches = df[df[col].astype(str).str.contains(
            "python|machine learning|data science|generative ai|web development",
            case=False,
            na=False,
            regex=True
        )]

        if len(matches) > 0:
            print(f"\nColumn: {col}")
            print("Matching rows:", len(matches))
            display(matches.head(3))

======================================================================
career_knowledge_base.csv

Column: job_description
Matching rows: 176

,category,job_title,job_description,skills,num_skills,description_length,posting_count
2909,Business Development,Business Development Manager (Remote),"AT DIGITAL SPICE, WE BELIEVE IN SUSTAINABLE, L...","['Crm Systems', 'Seo', 'Digital Marketing', 'W...",17,2042,1
2929,Business Development,Business Development Representative,ABOUT THE JOB: PERRY IS A WORKFORCE TRANSFORMA...,"['Sales Development', 'Cold-Calling', 'Prospec...",17,3530,33
2930,Business Development,Business Development Representative,ABOUT THE JOB: PERRY IS A WORKFORCE TRANSFORMA...,"['Sales Development', 'Cold-Calling', 'Prospec...",17,4494,33

Column: skills
Matching rows: 94

,category,job_title,job_description,skills,num_skills,description_length,posting_count
2909,Business Development,Business Development Manager (Remote),"AT DIGITAL SPICE, WE BELIEVE IN SUSTAINABLE, L...","['Crm Systems', 'Seo', 'Digital Marketing', 'W...",17,2042,1
3061,Business Development,Business Development Representative,"AT KALIBRI LABS, WE ARE HELPING TO REDEFINE AN...","['Microsoft Office', 'Communication', 'Collabo...",17,3530,33
3062,Business Development,Business Development Representative,"AT KALIBRI LABS, WE ARE HELPING TO REDEFINE AN...","['Microsoft Office', 'Communication', 'Collabo...",17,4494,33

======================================================================
course_knowledge_base.csv

Column: course_id
Matching rows: 26

,course_id,name,institution,average_rating,review_count,knowledge
3,accounting-data-analytics-python,accounting data analytics with python,university of illinois at urbana-champaign,3.285714,7,Course Name: accounting data analytics with py...
22,aprendiendo-programar-python,introducción a la programación en python i: ap...,pontificia universidad católica de chile,4.164627,899,Course Name: introducción a la programación en...
50,building-modern-python-applications-on-aws,building modern python applications on aws,amazon web services,5.000000,1,Course Name: building modern python applicatio...

Column: name
Matching rows: 54

,course_id,name,institution,average_rating,review_count,knowledge
3,accounting-data-analytics-python,accounting data analytics with python,university of illinois at urbana-champaign,3.285714,7,Course Name: accounting data analytics with py...
20,applied-data-science-capstone,applied data science capstone,ibm,4.461538,507,Course Name: applied data science capstone. In...
22,aprendiendo-programar-python,introducción a la programación en python i: ap...,pontificia universidad católica de chile,4.164627,899,Course Name: introducción a la programación en...

Column: knowledge
Matching rows: 103

,course_id,name,institution,average_rating,review_count,knowledge
3,accounting-data-analytics-python,accounting data analytics with python,university of illinois at urbana-champaign,3.285714,7,Course Name: accounting data analytics with py...
9,ai-for-everyone,ai for everyone,deeplearning.ai,4.854167,6144,Course Name: ai for everyone. Institution: dee...
10,ai-for-medical-diagnosis,ai for medical diagnosis,deeplearning.ai,4.587983,233,Course Name: ai for medical diagnosis. Institu...

======================================================================
core_knowledge_preprocessed.csv

Column: job_description
Matching rows: 32

,category,job_title,job_description,job_skill_set
33,hr,human resources specialist,"onsite jacksonville, floridanlp logix is sear...","hr practices, regulatory compliance, payroll a..."
219,hr,"data engineer enterprise data and analytics, ...",what youll dowere looking for a data engineer ...,"data security, data management, data analysis,..."
233,informationtechnology,analyst ii information technology,carpenter technology corporation is a leading ...,"hardware inventory management, organizational ..."

Column: job_skill_set
Matching rows: 21

,category,job_title,job_description,job_skill_set
219,hr,"data engineer enterprise data and analytics, ...",what youll dowere looking for a data engineer ...,"data security, data management, data analysis,..."
233,informationtechnology,analyst ii information technology,carpenter technology corporation is a leading ...,"hardware inventory management, organizational ..."
237,informationtechnology,information technology support technician,about us with over 400 employees and an annual...,"hardware support, software support, network tr..."

In [34]:
import pandas as pd
import os

base = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed"

course_df = pd.read_csv(
    os.path.join(base, "course_knowledge_base.csv")
)

# Search for the exact topics that appeared in your earlier RAG answers
topics = [
    "python",
    "machine learning",
    "data science",
    "generative ai",
    "web development"
]

for topic in topics:
    matches = course_df[
        course_df["knowledge"].astype(str).str.contains(
            topic,
            case=False,
            na=False
        )
    ]

    print(f"\n--- {topic.upper()} ---")
    print("Matches:", len(matches))

    if len(matches) > 0:
        display(
            matches[["course_id", "name", "knowledge"]].head(2)
        )

--- PYTHON ---
Matches: 71

,course_id,name,knowledge
3,accounting-data-analytics-python,accounting data analytics with python,Course Name: accounting data analytics with py...
10,ai-for-medical-diagnosis,ai for medical diagnosis,Course Name: ai for medical diagnosis. Institu...

--- MACHINE LEARNING ---
Matches: 30

,course_id,name,knowledge
9,ai-for-everyone,ai for everyone,Course Name: ai for everyone. Institution: dee...
11,ai-for-medical-prognosis,ai for medical prognosis,Course Name: ai for medical prognosis. Institu...

--- DATA SCIENCE ---
Matches: 27

,course_id,name,knowledge
9,ai-for-everyone,ai for everyone,Course Name: ai for everyone. Institution: dee...
10,ai-for-medical-diagnosis,ai for medical diagnosis,Course Name: ai for medical diagnosis. Institu...

--- GENERATIVE AI ---
Matches: 0

--- WEB DEVELOPMENT ---
Matches: 6

,course_id,name,knowledge
46,bootstrap-4,front-end web ui frameworks and tools: bootstr...,Course Name: front-end web ui frameworks and t...
140,django-database-web-apps,web application technologies and django,Course Name: web application technologies and ...

In [35]:
import pandas as pd
import os

base = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed"

core_df = pd.read_csv(
    os.path.join(base, "core_knowledge_preprocessed.csv")
)

# Search across all text columns
search_terms = [
    "python",
    "machine learning",
    "data science",
    "generative ai",
    "web development"
]

for term in search_terms:
    mask = core_df.astype(str).apply(
        lambda col: col.str.contains(term, case=False, na=False)
    ).any(axis=1)

    matches = core_df[mask]

    print(f"\n--- {term.upper()} ---")
    print("Matches:", len(matches))

    if len(matches) > 0:
        display(matches.head(3))

--- PYTHON ---
Matches: 14

,category,job_title,job_description,job_skill_set
219,hr,"data engineer enterprise data and analytics, ...",what youll dowere looking for a data engineer ...,"data security, data management, data analysis,..."
237,informationtechnology,information technology support technician,about us with over 400 employees and an annual...,"hardware support, software support, network tr..."
293,informationtechnology,information technology specialist,position overviewour innovation and technology...,"help desk support, customer service, networkin..."

--- MACHINE LEARNING ---
Matches: 12

,category,job_title,job_description,job_skill_set
33,hr,human resources specialist,"onsite jacksonville, floridanlp logix is sear...","hr practices, regulatory compliance, payroll a..."
233,informationtechnology,analyst ii information technology,carpenter technology corporation is a leading ...,"hardware inventory management, organizational ..."
269,informationtechnology,information technology engineer,"it engineer boca raton, fl onsite summarythe...","sql server 2012 administration, strong sense o..."

--- DATA SCIENCE ---
Matches: 8

,category,job_title,job_description,job_skill_set
33,hr,human resources specialist,"onsite jacksonville, floridanlp logix is sear...","hr practices, regulatory compliance, payroll a..."
219,hr,"data engineer enterprise data and analytics, ...",what youll dowere looking for a data engineer ...,"data security, data management, data analysis,..."
293,informationtechnology,information technology specialist,position overviewour innovation and technology...,"help desk support, customer service, networkin..."

--- GENERATIVE AI ---
Matches: 3

,category,job_title,job_description,job_skill_set
843,finance,finance analyst external reporting team,careers that change lives team is working hybr...,"financial reporting, data analysis, microsoft ..."
1068,businessdevelopment,business development representative,"at dataiku, were not just adapting to the ai r...","sales development, business development, data ..."
1164,businessdevelopment,enterprise business development representative...,join our dynamic ai team as an enterprise busi...,"salesforce, data analysis, lead generation, co..."

--- WEB DEVELOPMENT ---
Matches: 5

,category,job_title,job_description,job_skill_set
285,informationtechnology,information technology developer,it developer reporting analyst iionsite spri...,"sharepoint, teamwork, problem solving, custome..."
386,informationtechnology,information technology application manager,the commercial applications manager is a strat...,"project management, software development life ..."
450,informationtechnology,director of information technology,position summaryserve as a member of the aces ...,"web development, server administration, networ..."

In [ ]:
import pickle

# Save FAISS index
faiss.write_index(index, "faiss_index.index")

# Save knowledge chunks
with open("knowledge_chunks.pkl", "wb") as f:
    pickle.dump(chunks, f)

print("FAISS index saved successfully!")
print("Knowledge chunks saved successfully!")
print("Total chunks saved:", len(chunks))

In [ ]:
import faiss
import numpy as np

embedding_array = np.array(embeddings).astype("float32")

index = faiss.IndexFlatL2(embedding_array.shape[1])

index.add(embedding_array)

print("Total vectors in FAISS:", index.ntotal)

In [ ]:
query = "What should I learn to become a Python developer?"

query_embedding = embedding_model.encode([query])

query_embedding = np.array(query_embedding).astype("float32")

distances, indices = index.search(query_embedding, k=3)

print("Relevant chunks:\n")

for i, idx in enumerate(indices[0]):
    print(f"--- Result {i+1} ---")
    print("File:", chunks[idx]["filename"])
    print("Distance:", distances[0][i])
    print(chunks[idx]["content"])
    print()

In [ ]:
context = "\n\n".join(
    [chunks[idx]["content"] for idx in indices[0]]
)

print("Retrieved Context:\n")
print(context)

In [ ]:
!pip install -q openai

In [ ]:
import openai

print("OpenAI library installed successfully!")

In [ ]:
!pip install -q google-genai

In [ ]:
from google import genai
from google.colab import userdata

api_key = userdata.get("GEMINI_API_KEY")

client = genai.Client(api_key=api_key)

print("Gemini connected successfully!")

In [ ]:
prompt = f"""
You are an AI learning assistant.

Answer the student's question using ONLY the information
provided in the context below.

Context:
{context}

Student Question:
{query}

Give a clear and simple answer suitable for a student.
"""

response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents=prompt
)

print(response.text)

In [ ]:
query = "What should I learn before starting Machine Learning?"

query_embedding = embedding_model.encode([query])
query_embedding = np.array(query_embedding).astype("float32")

distances, indices = index.search(query_embedding, k=3)

print("Question:", query)
print("\nRelevant chunks:\n")

for i, idx in enumerate(indices[0]):
    print(f"--- Result {i+1} ---")
    print("File:", chunks[idx]["filename"])
    print("Distance:", distances[0][i])
    print(chunks[idx]["content"])
    print()

In [ ]:
query = "What should I learn to become a web developer?"

query_embedding = embedding_model.encode([query])
query_embedding = np.array(query_embedding).astype("float32")

distances, indices = index.search(query_embedding, k=3)

print("Question:", query)
print("\nRelevant chunks:\n")

for i, idx in enumerate(indices[0]):
    print(f"--- Result {i+1} ---")
    print("File:", chunks[idx]["filename"])
    print("Distance:", distances[0][i])
    print(chunks[idx]["content"])
    print()

In [ ]:
query = "What should I learn to get started with Generative AI?"

query_embedding = embedding_model.encode([query])
query_embedding = np.array(query_embedding).astype("float32")

distances, indices = index.search(query_embedding, k=3)

print("Question:", query)
print("\nRelevant chunks:\n")

for i, idx in enumerate(indices[0]):
    print(f"--- Result {i+1} ---")
    print("File:", chunks[idx]["filename"])
    print("Distance:", distances[0][i])
    print(chunks[idx]["content"])
    print()

In [ ]:
def ask_rag(question, k=3):

    # 1. Convert question into embedding
    query_embedding = embedding_model.encode([question])
    query_embedding = np.array(query_embedding).astype("float32")

    # 2. Search FAISS
    distances, indices = index.search(query_embedding, k)

    # 3. Create context from retrieved chunks
    context = "\n\n".join(
        [chunks[idx]["content"] for idx in indices[0]]
    )

    # 4. Create prompt
    prompt = f"""
You are an AI learning assistant.

Answer the student's question using ONLY the information
provided in the context below.

Context:
{context}

Student Question:
{question}

Give a clear, simple and useful answer suitable for a student.
"""

    # 5. Generate answer using Gemini
    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt
    )

    return response.text

In [ ]:
question = "What should I learn to become a data scientist?"

answer = ask_rag(question)

print("Question:", question)
print("\nRAG Answer:\n")
print(answer)

In [ ]:
import os

os.makedirs("rag_data", exist_ok=True)

print("rag_data folder created!")

In [ ]:
import faiss

faiss.write_index(index, "rag_data/knowledge_base.index")

print("FAISS index saved successfully!")

In [ ]:
import pickle

with open("rag_data/knowledge_chunks.pkl", "wb") as f:
    pickle.dump(chunks, f)

print("Knowledge chunks saved successfully!")
print("Total chunks saved:", len(chunks))

In [ ]:
import faiss

loaded_index = faiss.read_index("rag_data/knowledge_base.index")

print("FAISS index loaded successfully!")
print("Total vectors:", loaded_index.ntotal)

In [ ]:
import pickle

with open("rag_data/knowledge_chunks.pkl", "rb") as f:
    loaded_chunks = pickle.load(f)

print("Knowledge chunks loaded successfully!")
print("Total chunks:", len(loaded_chunks))

In [ ]:
query = "What should I learn to become a Python developer?"

query_embedding = embedding_model.encode([query])
query_embedding = np.array(query_embedding).astype("float32")

distances, indices = loaded_index.search(query_embedding, k=3)

context = "\n\n".join(
    [loaded_chunks[idx]["content"] for idx in indices[0]]
)

print("Retrieved Context:\n")
print(context)

In [ ]:
answer = ask_rag("What should I learn to become a data scientist?")