In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
file_path = "/content/drive/MyDrive/AI POWERED PERSONALIZED LEARNING PATH GENERATOR/required datasets/Dataset Project 404.xlsx"

In [3]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [5]:
import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    if "Dataset Project 404.xlsx" in files:
        print(os.path.join(root, "Dataset Project 404.xlsx"))

/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/Dataset Project 404.xlsx

In [6]:
file_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/Dataset Project 404.xlsx"

df = pd.read_excel(file_path, sheet_name="original")

In [7]:
df.head()

,Sr.No.,Course,Job profession,Student,Linguistic,Musical,Bodily,Logical - Mathematical,Spatial-Visualization,Interpersonal,Intrapersonal,Naturalist,s/p,P1,P2,P3,P4,P5,P6,P7,P8
0,1.0,NaN,Astronomer\n,S1,11,5,12,16,17,11,18,19,s1,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
1,NaN,NaN,Astronomer\n,S2,12,6,12,16,16,11,18,19,s2,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
2,NaN,NaN,Astronomer\n,S3,13,7,12,16,15,11,18,19,s3,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
3,NaN,NaN,Astronomer\n,S4,14,8,12,16,19,11,18,19,s4,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
4,NaN,NaN,Astronomer\n,S5,13,9,12,16,20,11,19,19,s5,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST

In [8]:
# Dataset Shape

print("Number of Rows :", df.shape[0])
print("Number of Columns :", df.shape[1])

Number of Rows : 3600
Number of Columns : 21

In [9]:
df.columns.tolist()

['Sr.No.',
 'Course',
 'Job profession',
 'Student',
 'Linguistic',
 'Musical',
 'Bodily',
 'Logical - Mathematical',
 'Spatial-Visualization',
 'Interpersonal',
 'Intrapersonal',
 'Naturalist',
 's/p',
 'P1',
 'P2',
 'P3',
 'P4',
 'P5',
 'P6',
 'P7',
 'P8']

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sr.No.                  72 non-null     float64
 1   Course                  0 non-null      float64
 2   Job profession          3600 non-null   object
 3   Student                 3600 non-null   object
 4   Linguistic              3600 non-null   int64
 5   Musical                 3600 non-null   int64
 6   Bodily                  3600 non-null   int64
 7   Logical - Mathematical  3600 non-null   int64
 8   Spatial-Visualization   3600 non-null   int64
 9   Interpersonal           3600 non-null   int64
 10  Intrapersonal           3600 non-null   int64
 11  Naturalist              3600 non-null   int64
 12  s/p                     3600 non-null   object
 13  P1                      3600 non-null   object
 14  P2                      3600 non-null   object
 15  P3                      3600 non-null   object
 16  P4                      3600 non-null   object
 17  P5                      3600 non-null   object
 18  P6                      3594 non-null   object
 19  P7                      3600 non-null   object
 20  P8                      3599 non-null   object
dtypes: float64(2), int64(8), object(11)
memory usage: 590.8+ KB

In [11]:
df.dtypes

Sr.No.                    float64
Course                    float64
Job profession             object
Student                    object
Linguistic                  int64
Musical                     int64
Bodily                      int64
Logical - Mathematical      int64
Spatial-Visualization       int64
Interpersonal               int64
Intrapersonal               int64
Naturalist                  int64
s/p                        object
P1                         object
P2                         object
P3                         object
P4                         object
P5                         object
P6                         object
P7                         object
P8                         object
dtype: object

In [12]:
missing_values = df.isnull().sum()

missing_values

Sr.No.                    3528
Course                    3600
Job profession               0
Student                      0
Linguistic                   0
Musical                      0
Bodily                       0
Logical - Mathematical       0
Spatial-Visualization        0
Interpersonal                0
Intrapersonal                0
Naturalist                   0
s/p                          0
P1                           0
P2                           0
P3                           0
P4                           0
P5                           0
P6                           6
P7                           0
P8                           1
dtype: int64

In [13]:
duplicates = df.duplicated().sum()

print("Duplicate Records :", duplicates)

Duplicate Records : 0

In [14]:
df.isnull().sum()

Sr.No.                    3528
Course                    3600
Job profession               0
Student                      0
Linguistic                   0
Musical                      0
Bodily                       0
Logical - Mathematical       0
Spatial-Visualization        0
Interpersonal                0
Intrapersonal                0
Naturalist                   0
s/p                          0
P1                           0
P2                           0
P3                           0
P4                           0
P5                           0
P6                           6
P7                           0
P8                           1
dtype: int64

In [15]:
df["Course"].unique()

array([nan])

In [16]:
df[df["P6"].isnull()]

,Sr.No.,Course,Job profession,Student,Linguistic,Musical,Bodily,Logical - Mathematical,Spatial-Visualization,Interpersonal,Intrapersonal,Naturalist,s/p,P1,P2,P3,P4,P5,P6,P7,P8
1500,31.0,NaN,Dancer,S1501,5,20,18,5,11,2,11,14,s1501,POOR,BEST,BEST,POOR,AVG,NaN,AVG,AVG
1501,NaN,NaN,Dancer,S1502,6,19,18,6,11,2,11,12,s1502,POOR,BEST,BEST,POOR,AVG,NaN,AVG,AVG
1502,NaN,NaN,Dancer,S1503,7,18,18,7,12,2,12,11,s1503,POOR,BEST,BEST,POOR,AVG,NaN,AVG,AVG
1503,NaN,NaN,Dancer,S1504,8,17,18,8,12,2,12,12,s1504,POOR,BEST,BEST,POOR,AVG,NaN,AVG,AVG
1504,NaN,NaN,Dancer,S1505,9,16,18,9,13,2,13,12,s1505,POOR,BEST,BEST,POOR,AVG,NaN,AVG,AVG
1505,NaN,NaN,Dancer,S1506,10,15,18,10,12,2,12,13,s1506,POOR,BEST,BEST,POOR,AVG,NaN,AVG,AVG

In [17]:
df[df["P8"].isnull()]

,Sr.No.,Course,Job profession,Student,Linguistic,Musical,Bodily,Logical - Mathematical,Spatial-Visualization,Interpersonal,Intrapersonal,Naturalist,s/p,P1,P2,P3,P4,P5,P6,P7,P8
801,NaN,NaN,Engineer,S802,12,5,6,17,19,12,19,0,s802,AVG,POOR,POOR,BEST,BEST,AVG,BEST,NaN

In [18]:
print("Duplicate Records:", df.duplicated().sum())

Duplicate Records: 0

In [19]:
# Remove the Course column

df.drop(columns=["Course"], inplace=True)

print("Course column removed successfully.")

Course column removed successfully.

In [20]:
df.columns

Index(['Sr.No.', 'Job profession', 'Student', 'Linguistic', 'Musical',
       'Bodily', 'Logical - Mathematical', 'Spatial-Visualization',
       'Interpersonal', 'Intrapersonal', 'Naturalist', 's/p', 'P1', 'P2', 'P3',
       'P4', 'P5', 'P6', 'P7', 'P8'],
      dtype='object')

In [21]:
# Forward fill the Sr.No. column

df["Sr.No."] = df["Sr.No."].ffill()

print("Missing values in Sr.No. :", df["Sr.No."].isnull().sum())

Missing values in Sr.No. : 0

In [22]:
# Display the first 10 rows

df.head(10)

,Sr.No.,Job profession,Student,Linguistic,Musical,Bodily,Logical - Mathematical,Spatial-Visualization,Interpersonal,Intrapersonal,Naturalist,s/p,P1,P2,P3,P4,P5,P6,P7,P8
0,1.0,Astronomer\n,S1,11,5,12,16,17,11,18,19,s1,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
1,1.0,Astronomer\n,S2,12,6,12,16,16,11,18,19,s2,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
2,1.0,Astronomer\n,S3,13,7,12,16,15,11,18,19,s3,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
3,1.0,Astronomer\n,S4,14,8,12,16,19,11,18,19,s4,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
4,1.0,Astronomer\n,S5,13,9,12,16,20,11,19,19,s5,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
5,1.0,Astronomer\n,S6,12,8,12,16,17,11,19,19,s6,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
6,1.0,Astronomer\n,S7,11,7,12,16,16,11,19,19,s7,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
7,1.0,Astronomer\n,S8,14,6,12,16,15,11,19,19,s8,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
8,1.0,Astronomer\n,S9,11,5,12,16,19,11,19,19,s9,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
9,1.0,Astronomer\n,S10,12,5,13,16,20,12,19,19,s10,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST

In [23]:
# Remove newline characters and leading/trailing spaces

df["Job profession"] = (
    df["Job profession"]
    .str.replace("\n", "", regex=False)
    .str.strip()
)

print("Job profession column cleaned successfully.")

Job profession column cleaned successfully.

In [24]:
# Display the first 10 job professions

df["Job profession"].head(10)

0    Astronomer
1    Astronomer
2    Astronomer
3    Astronomer
4    Astronomer
5    Astronomer
6    Astronomer
7    Astronomer
8    Astronomer
9    Astronomer
Name: Job profession, dtype: object

In [25]:
# Convert s/p values to uppercase

df["s/p"] = df["s/p"].str.upper()

print("s/p column standardized successfully.")

s/p column standardized successfully.

In [26]:
df[["Student", "s/p"]].head(10)

  Student  s/p
0      S1   S1
1      S2   S2
2      S3   S3
3      S4   S4
4      S5   S5
5      S6   S6
6      S7   S7
7      S8   S8
8      S9   S9
9     S10  S10

In [28]:
# Rows with missing values in P6

df[df["P6"].isnull()]

,Sr.No.,Job profession,Student,Linguistic,Musical,Bodily,Logical - Mathematical,Spatial-Visualization,Interpersonal,Intrapersonal,Naturalist,s/p,P1,P2,P3,P4,P5,P6,P7,P8
1500,31.0,Dancer,S1501,5,20,18,5,11,2,11,14,S1501,POOR,BEST,BEST,POOR,AVG,NaN,AVG,AVG
1501,31.0,Dancer,S1502,6,19,18,6,11,2,11,12,S1502,POOR,BEST,BEST,POOR,AVG,NaN,AVG,AVG
1502,31.0,Dancer,S1503,7,18,18,7,12,2,12,11,S1503,POOR,BEST,BEST,POOR,AVG,NaN,AVG,AVG
1503,31.0,Dancer,S1504,8,17,18,8,12,2,12,12,S1504,POOR,BEST,BEST,POOR,AVG,NaN,AVG,AVG
1504,31.0,Dancer,S1505,9,16,18,9,13,2,13,12,S1505,POOR,BEST,BEST,POOR,AVG,NaN,AVG,AVG
1505,31.0,Dancer,S1506,10,15,18,10,12,2,12,13,S1506,POOR,BEST,BEST,POOR,AVG,NaN,AVG,AVG

In [29]:
# Rows with missing values in P8

df[df["P8"].isnull()]

,Sr.No.,Job profession,Student,Linguistic,Musical,Bodily,Logical - Mathematical,Spatial-Visualization,Interpersonal,Intrapersonal,Naturalist,s/p,P1,P2,P3,P4,P5,P6,P7,P8
801,17.0,Engineer,S802,12,5,6,17,19,12,19,0,S802,AVG,POOR,POOR,BEST,BEST,AVG,BEST,NaN

In [30]:
# Fill missing values using the mode

df["P6"] = df["P6"].fillna(df["P6"].mode()[0])
df["P8"] = df["P8"].fillna(df["P8"].mode()[0])

print("Missing values handled successfully.")

Missing values handled successfully.

In [31]:
# Check remaining missing values

df.isnull().sum()

Sr.No.                    0
Job profession            0
Student                   0
Linguistic                0
Musical                   0
Bodily                    0
Logical - Mathematical    0
Spatial-Visualization     0
Interpersonal             0
Intrapersonal             0
Naturalist                0
s/p                       0
P1                        0
P2                        0
P3                        0
P4                        0
P5                        0
P6                        0
P7                        0
P8                        0
dtype: int64

In [32]:
# Rename columns for consistency

df.rename(columns={
    "Sr.No.": "Sr_No",
    "Job profession": "Job_Profession",
    "Logical - Mathematical": "Logical_Mathematical",
    "Spatial-Visualization": "Spatial_Visualization",
    "s/p": "Student_ID"
}, inplace=True)

print("Column names renamed successfully.")

Column names renamed successfully.

In [33]:
df.columns.tolist()

['Sr_No',
 'Job_Profession',
 'Student',
 'Linguistic',
 'Musical',
 'Bodily',
 'Logical_Mathematical',
 'Spatial_Visualization',
 'Interpersonal',
 'Intrapersonal',
 'Naturalist',
 'Student_ID',
 'P1',
 'P2',
 'P3',
 'P4',
 'P5',
 'P6',
 'P7',
 'P8']

In [34]:
# Dataset information after preprocessing

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Sr_No                  3600 non-null   float64
 1   Job_Profession         3600 non-null   object
 2   Student                3600 non-null   object
 3   Linguistic             3600 non-null   int64
 4   Musical                3600 non-null   int64
 5   Bodily                 3600 non-null   int64
 6   Logical_Mathematical   3600 non-null   int64
 7   Spatial_Visualization  3600 non-null   int64
 8   Interpersonal          3600 non-null   int64
 9   Intrapersonal          3600 non-null   int64
 10  Naturalist             3600 non-null   int64
 11  Student_ID             3600 non-null   object
 12  P1                     3600 non-null   object
 13  P2                     3600 non-null   object
 14  P3                     3600 non-null   object
 15  P4                     3600 non-null   object
 16  P5                     3600 non-null   object
 17  P6                     3600 non-null   object
 18  P7                     3600 non-null   object
 19  P8                     3600 non-null   object
dtypes: float64(1), int64(8), object(11)
memory usage: 562.6+ KB

In [35]:
# Display the first five rows

df.head()

,Sr_No,Job_Profession,Student,Linguistic,Musical,Bodily,Logical_Mathematical,Spatial_Visualization,Interpersonal,Intrapersonal,Naturalist,Student_ID,P1,P2,P3,P4,P5,P6,P7,P8
0,1.0,Astronomer,S1,11,5,12,16,17,11,18,19,S1,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
1,1.0,Astronomer,S2,12,6,12,16,16,11,18,19,S2,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
2,1.0,Astronomer,S3,13,7,12,16,15,11,18,19,S3,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
3,1.0,Astronomer,S4,14,8,12,16,19,11,18,19,S4,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
4,1.0,Astronomer,S5,13,9,12,16,20,11,19,19,S5,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST

In [36]:
# Display the last five rows

df.tail()

,Sr_No,Job_Profession,Student,Linguistic,Musical,Bodily,Logical_Mathematical,Spatial_Visualization,Interpersonal,Intrapersonal,Naturalist,Student_ID,P1,P2,P3,P4,P5,P6,P7,P8
3595,72.0,Technician,S3596,8,7,15,12,14,15,14,11,S3596,POOR,POOR,BEST,AVG,AVG,BEST,AVG,AVG
3596,72.0,Technician,S3597,9,8,16,11,13,16,14,12,S3597,POOR,POOR,BEST,AVG,AVG,BEST,AVG,AVG
3597,72.0,Technician,S3598,10,8,17,12,11,17,14,14,S3598,POOR,POOR,BEST,AVG,AVG,BEST,AVG,AVG
3598,72.0,Technician,S3599,6,9,19,13,13,18,13,11,S3599,POOR,POOR,BEST,AVG,AVG,BEST,AVG,AVG
3599,72.0,Technician,S3600,8,9,18,14,14,19,14,11,S3600,POOR,POOR,BEST,AVG,AVG,BEST,AVG,AVG

In [37]:
# Convert Sr_No to integer

df["Sr_No"] = df["Sr_No"].astype(int)

print(df["Sr_No"].dtype)

int64

In [38]:
# Save the cleaned dataset

output_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_dataset_cleaned.csv"

df.to_csv(output_path, index=False)

print("Student dataset saved successfully!")
print(output_path)

Student dataset saved successfully!
/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_dataset_cleaned.csv