In [1]:
import pandas as pd
import numpy as np
import json

pd.set_option("display.max_columns", None)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
file_path="/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_dataset_cleaned.csv"

df=pd.read_csv(file_path)

In [4]:
df.head()

,Sr_No,Job_Profession,Student,Linguistic,Musical,Bodily,Logical_Mathematical,Spatial_Visualization,Interpersonal,Intrapersonal,Naturalist,Student_ID,P1,P2,P3,P4,P5,P6,P7,P8
0,1,Astronomer,S1,11,5,12,16,17,11,18,19,S1,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
1,1,Astronomer,S2,12,6,12,16,16,11,18,19,S2,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
2,1,Astronomer,S3,13,7,12,16,15,11,18,19,S3,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
3,1,Astronomer,S4,14,8,12,16,19,11,18,19,S4,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
4,1,Astronomer,S5,13,9,12,16,20,11,19,19,S5,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Sr_No                  3600 non-null   int64
 1   Job_Profession         3600 non-null   object
 2   Student                3600 non-null   object
 3   Linguistic             3600 non-null   int64
 4   Musical                3600 non-null   int64
 5   Bodily                 3600 non-null   int64
 6   Logical_Mathematical   3600 non-null   int64
 7   Spatial_Visualization  3600 non-null   int64
 8   Interpersonal          3600 non-null   int64
 9   Intrapersonal          3600 non-null   int64
 10  Naturalist             3600 non-null   int64
 11  Student_ID             3600 non-null   object
 12  P1                     3600 non-null   object
 13  P2                     3600 non-null   object
 14  P3                     3600 non-null   object
 15  P4                     3600 non-null   object
 16  P5                     3600 non-null   object
 17  P6                     3600 non-null   object
 18  P7                     3600 non-null   object
 19  P8                     3600 non-null   object
dtypes: int64(9), object(11)
memory usage: 562.6+ KB

In [6]:
# Create student profiles

student_profiles = df[[
    "Student_ID",
    "Student",
    "Job_Profession"
]].copy()

student_profiles.head()

  Student_ID Student Job_Profession
0         S1      S1     Astronomer
1         S2      S2     Astronomer
2         S3      S3     Astronomer
3         S4      S4     Astronomer
4         S5      S5     Astronomer

In [7]:
# Save student profiles

output_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_profiles.csv"

student_profiles.to_csv(output_path, index=False)

print("Student Profiles saved successfully!")

Student Profiles saved successfully!

In [8]:
# Save student profiles as JSON

json_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_profiles.json"

student_profiles.to_json(
    json_path,
    orient="records",
    indent=4
)

print("Student Profiles JSON saved successfully!")

Student Profiles JSON saved successfully!

In [9]:
# Create intelligence profiles

student_intelligence_profiles = df[[
    "Student_ID",
    "Linguistic",
    "Musical",
    "Bodily",
    "Logical_Mathematical",
    "Spatial_Visualization",
    "Interpersonal",
    "Intrapersonal",
    "Naturalist"
]].copy()

student_intelligence_profiles.head()

,Student_ID,Linguistic,Musical,Bodily,Logical_Mathematical,Spatial_Visualization,Interpersonal,Intrapersonal,Naturalist
0,S1,11,5,12,16,17,11,18,19
1,S2,12,6,12,16,16,11,18,19
2,S3,13,7,12,16,15,11,18,19
3,S4,14,8,12,16,19,11,18,19
4,S5,13,9,12,16,20,11,19,19

In [10]:
# Save intelligence profiles

output_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_intelligence_profiles.csv"

student_intelligence_profiles.to_csv(output_path, index=False)

print("Student Intelligence Profiles saved successfully!")

Student Intelligence Profiles saved successfully!

In [11]:
# Intelligence columns

intelligence_columns = [
    "Linguistic",
    "Musical",
    "Bodily",
    "Logical_Mathematical",
    "Spatial_Visualization",
    "Interpersonal",
    "Intrapersonal",
    "Naturalist"
]

# Create Dominant Intelligence feature

df["Dominant_Intelligence"] = df[intelligence_columns].idxmax(axis=1)

df[["Student_ID", "Dominant_Intelligence"]].head(10)

  Student_ID  Dominant_Intelligence
0         S1             Naturalist
1         S2             Naturalist
2         S3             Naturalist
3         S4  Spatial_Visualization
4         S5  Spatial_Visualization
5         S6          Intrapersonal
6         S7          Intrapersonal
7         S8          Intrapersonal
8         S9  Spatial_Visualization
9        S10  Spatial_Visualization

In [12]:
# Count of dominant intelligence types

df["Dominant_Intelligence"].value_counts()

Dominant_Intelligence
Logical_Mathematical     1055
Interpersonal             738
Linguistic                477
Bodily                    381
Intrapersonal             357
Musical                   238
Naturalist                210
Spatial_Visualization     144
Name: count, dtype: int64

In [13]:
# Create Average Intelligence Score

df["Average_Intelligence_Score"] = (
    df[intelligence_columns]
    .mean(axis=1)
    .round(2)
)

df[[
    "Student_ID",
    "Average_Intelligence_Score"
]].head(10)

  Student_ID  Average_Intelligence_Score
0         S1                       13.62
1         S2                       13.75
2         S3                       13.88
3         S4                       14.62
4         S5                       14.88
5         S6                       14.25
6         S7                       13.88
7         S8                       14.00
8         S9                       14.00
9        S10                       14.50

In [14]:
# Summary statistics

df["Average_Intelligence_Score"].describe()

count    3600.000000
mean       12.663917
std         0.868003
min         9.620000
25%        12.120000
50%        12.750000
75%        13.250000
max        15.500000
Name: Average_Intelligence_Score, dtype: float64

In [15]:
# Convert performance ratings into numerical scores

performance_mapping = {
    "POOR": 1,
    "AVG": 2,
    "BEST": 3
}

performance_columns = [
    "P1", "P2", "P3", "P4",
    "P5", "P6", "P7", "P8"
]

performance_scores = df[performance_columns].replace(performance_mapping)

# Create Average Performance feature

df["Average_Performance"] = (
    performance_scores
    .mean(axis=1)
    .round(2)
)

df[[
    "Student_ID",
    "Average_Performance"
]].head(10)

/tmp/ipykernel_4017/156036481.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  performance_scores = df[performance_columns].replace(performance_mapping)

  Student_ID  Average_Performance
0         S1                 2.38
1         S2                 2.38
2         S3                 2.38
3         S4                 2.38
4         S5                 2.38
5         S6                 2.38
6         S7                 2.38
7         S8                 2.38
8         S9                 2.38
9        S10                 2.38

In [16]:
# Summary statistics

df["Average_Performance"].describe()

count    3600.000000
mean        2.048750
std         0.129546
min         1.750000
25%         2.000000
50%         2.120000
75%         2.120000
max         2.380000
Name: Average_Performance, dtype: float64

In [17]:
# Create Performance Category

def performance_category(score):
    if score >= 2.30:
        return "Excellent"
    elif score >= 2.00:
        return "Good"
    else:
        return "Average"

df["Performance_Category"] = df["Average_Performance"].apply(performance_category)

df[[
    "Student_ID",
    "Average_Performance",
    "Performance_Category"
]].head(10)

  Student_ID  Average_Performance Performance_Category
0         S1                 2.38            Excellent
1         S2                 2.38            Excellent
2         S3                 2.38            Excellent
3         S4                 2.38            Excellent
4         S5                 2.38            Excellent
5         S6                 2.38            Excellent
6         S7                 2.38            Excellent
7         S8                 2.38            Excellent
8         S9                 2.38            Excellent
9        S10                 2.38            Excellent

In [18]:
# Count of performance categories

df["Performance_Category"].value_counts()

Performance_Category
Good         2950
Average       600
Excellent      50
Name: count, dtype: int64

In [19]:
# Create student statistics

student_statistics = pd.DataFrame({
    "Metric": [
        "Total Students",
        "Unique Job Professions",
        "Average Intelligence Score",
        "Average Performance Score",
        "Highest Average Intelligence Score",
        "Lowest Average Intelligence Score"
    ],
    "Value": [
        len(df),
        df["Job_Profession"].nunique(),
        round(df["Average_Intelligence_Score"].mean(), 2),
        round(df["Average_Performance"].mean(), 2),
        round(df["Average_Intelligence_Score"].max(), 2),
        round(df["Average_Intelligence_Score"].min(), 2)
    ]
})

student_statistics

                               Metric    Value
0                      Total Students  3600.00
1              Unique Job Professions    72.00
2          Average Intelligence Score    12.66
3           Average Performance Score     2.05
4  Highest Average Intelligence Score    15.50
5   Lowest Average Intelligence Score     9.62

In [20]:
# Save statistics

output_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_statistics.csv"

student_statistics.to_csv(output_path, index=False)

print("Student Statistics saved successfully!")

Student Statistics saved successfully!

In [21]:
# Create Student Knowledge Base

student_knowledge_base = df[[
    "Student_ID",
    "Job_Profession",
    "Dominant_Intelligence",
    "Average_Intelligence_Score",
    "Average_Performance",
    "Performance_Category"
]].copy()

student_knowledge_base.head()

,Student_ID,Job_Profession,Dominant_Intelligence,Average_Intelligence_Score,Average_Performance,Performance_Category
0,S1,Astronomer,Naturalist,13.62,2.38,Excellent
1,S2,Astronomer,Naturalist,13.75,2.38,Excellent
2,S3,Astronomer,Naturalist,13.88,2.38,Excellent
3,S4,Astronomer,Spatial_Visualization,14.62,2.38,Excellent
4,S5,Astronomer,Spatial_Visualization,14.88,2.38,Excellent

In [22]:
# Save Student Knowledge Base

output_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_knowledge_base.csv"

student_knowledge_base.to_csv(output_path, index=False)

print("Student Knowledge Base saved successfully!")

Student Knowledge Base saved successfully!

In [23]:
# Save Student Knowledge Base as JSON

json_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_knowledge_base.json"

student_knowledge_base.to_json(
    json_path,
    orient="records",
    indent=4
)

print("Student Knowledge Base JSON saved successfully!")

Student Knowledge Base JSON saved successfully!

In [24]:
# Save the feature-engineered dataset

output_path = "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/required datasets/student_dataset_feature_engineered.csv"

df.to_csv(output_path, index=False)

print("Feature Engineered Dataset saved successfully!")

Feature Engineered Dataset saved successfully!

In [25]:
print("Student Profiles")
display(student_profiles.head())

print("\nStudent Intelligence Profiles")
display(student_intelligence_profiles.head())

print("\nStudent Statistics")
display(student_statistics)

print("\nStudent Knowledge Base")
display(student_knowledge_base.head())

Student Profiles

  Student_ID Student Job_Profession
0         S1      S1     Astronomer
1         S2      S2     Astronomer
2         S3      S3     Astronomer
3         S4      S4     Astronomer
4         S5      S5     Astronomer

Student Intelligence Profiles

,Student_ID,Linguistic,Musical,Bodily,Logical_Mathematical,Spatial_Visualization,Interpersonal,Intrapersonal,Naturalist
0,S1,11,5,12,16,17,11,18,19
1,S2,12,6,12,16,16,11,18,19
2,S3,13,7,12,16,15,11,18,19
3,S4,14,8,12,16,19,11,18,19
4,S5,13,9,12,16,20,11,19,19

Student Statistics

                               Metric    Value
0                      Total Students  3600.00
1              Unique Job Professions    72.00
2          Average Intelligence Score    12.66
3           Average Performance Score     2.05
4  Highest Average Intelligence Score    15.50
5   Lowest Average Intelligence Score     9.62

Student Knowledge Base

,Student_ID,Job_Profession,Dominant_Intelligence,Average_Intelligence_Score,Average_Performance,Performance_Category
0,S1,Astronomer,Naturalist,13.62,2.38,Excellent
1,S2,Astronomer,Naturalist,13.75,2.38,Excellent
2,S3,Astronomer,Naturalist,13.88,2.38,Excellent
3,S4,Astronomer,Spatial_Visualization,14.62,2.38,Excellent
4,S5,Astronomer,Spatial_Visualization,14.88,2.38,Excellent