In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import ast

In [4]:
df = pd.read_csv(
    "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_dataset_cleaned.csv"
)

In [5]:
df

,category,job_title,job_description,job_skill_set
0,HR,Sr Human Resource Generalist,THE SR. HR GENERALIST PROVIDES HR EXPERTISE AC...,"['Employee Relations', 'Talent Acquisition', '..."
1,HR,Human Resources Manager,BE PART OF A STELLAR TEAM AT YSB AS THE MANAGE...,"['Talent Acquisition', 'Employee Performance M..."
2,HR,Director of Human Resources,OUR CLIENT IS A THRIVING ORGANIZATION OFFERING...,"['Human Resources Management', 'Recruitment', ..."
3,HR,Chief Human Resources Officer,CHIEF HUMAN RESOURCES OFFICER (CHRO)INDUSTRY: ...,"['Talent Management', 'Organizational Developm..."
4,HR,Human Resources Generalist (Hybrid Role),WHO WE ARE AVI-SPL IS A DIGITAL ENABLEMENT SOL...,"['Microsoft Office', 'Data Analysis', 'Employe..."
...,...,...,...,...
1162,Business Development,Intern - Business Development,DESCRIPTION & REQUIREMENTS THIS INDIVIDUAL WIL...,"['Ms Office Suite', 'Powerpoint', 'Excel', 'Re..."
1163,Business Development,Business Development Representative,IT'S FUN TO WORK IN A COMPANY WHERE PEOPLE TRU...,"['Collaboration', 'Communication', 'Problem So..."
1164,Business Development,Enterprise Business Development Representative...,JOIN OUR DYNAMIC AI TEAM AS AN ENTERPRISE BUSI...,"['Salesforce', 'Data Analysis', 'Lead Generati..."
1165,Business Development,Senior Director Business Development,ROOM 8 GROUP IS THE WORLD’S FASTEST GROWING ST...,"['Business Development', 'Sales', 'Corporate S..."
1166,Business Development,Global Business Development Partner - 100% Remote,EXCITING OPPORTUNITY: GLOBAL BUSINESS DEVELOPM...,"['Strategic Marketing', 'Business Development'..."

In [6]:
df["job_skill_set"] = df["job_skill_set"].apply(ast.literal_eval)

In [7]:
df.head()

,category,job_title,job_description,job_skill_set
0,HR,Sr Human Resource Generalist,THE SR. HR GENERALIST PROVIDES HR EXPERTISE AC...,"[Employee Relations, Talent Acquisition, Perfo..."
1,HR,Human Resources Manager,BE PART OF A STELLAR TEAM AT YSB AS THE MANAGE...,"[Talent Acquisition, Employee Performance Mana..."
2,HR,Director of Human Resources,OUR CLIENT IS A THRIVING ORGANIZATION OFFERING...,"[Human Resources Management, Recruitment, Empl..."
3,HR,Chief Human Resources Officer,CHIEF HUMAN RESOURCES OFFICER (CHRO)INDUSTRY: ...,"[Talent Management, Organizational Development..."
4,HR,Human Resources Generalist (Hybrid Role),WHO WE ARE AVI-SPL IS A DIGITAL ENABLEMENT SOL...,"[Microsoft Office, Data Analysis, Employee Onb..."

In [8]:
df["job_skill_set"].head()

0    [Employee Relations, Talent Acquisition, Perfo...
1    [Talent Acquisition, Employee Performance Mana...
2    [Human Resources Management, Recruitment, Empl...
3    [Talent Management, Organizational Development...
4    [Microsoft Office, Data Analysis, Employee Onb...
Name: job_skill_set, dtype: object

In [9]:
def normalize_skills(skill_list):
    normalized = []

    for skill in skill_list:
        skill = skill.strip()      # Remove leading/trailing spaces
        skill = skill.title()      # Standardize capitalization
        normalized.append(skill)

    return normalized

# Apply normalization
df["job_skill_set"] = df["job_skill_set"].apply(normalize_skills)

In [10]:
df["job_skill_set"].head()

0    [Employee Relations, Talent Acquisition, Perfo...
1    [Talent Acquisition, Employee Performance Mana...
2    [Human Resources Management, Recruitment, Empl...
3    [Talent Management, Organizational Development...
4    [Microsoft Office, Data Analysis, Employee Onb...
Name: job_skill_set, dtype: object

In [11]:
from collections import Counter

all_skills = []

for skills in df["job_skill_set"]:
    all_skills.extend(skills)

print("Total Skills:", len(all_skills))
print("Unique Skills:", len(set(all_skills)))

Total Skills: 20833
Unique Skills: 4984

In [12]:
df.to_csv(
    "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_dataset_feature_engineered.csv",
    index=False
)

In [13]:
# Create a set of unique skills
unique_skills = sorted(set(all_skills))

print("Total Unique Skills:", len(unique_skills))

Total Unique Skills: 4984

In [14]:
skill_vocab = pd.DataFrame({
    "Skill": unique_skills
})

skill_vocab.head(10)

                   Skill
0                   .Net
1       .Net Programming
2                    3Cx
3           3Pl Services
4  401(K) Administration
5      401(K) Management
6    401K Administration
7         401K Knowledge
8                 6Sense
9       A+ Certification

In [15]:
skill_vocab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4984 entries, 0 to 4983
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Skill   4984 non-null   object
dtypes: object(1)
memory usage: 39.1+ KB

In [16]:
skill_vocab.to_csv(
    "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/skill_vocabulary.csv",
    index=False
)

print("Skill vocabulary saved successfully!")

Skill vocabulary saved successfully!

In [17]:
career_skill_mapping = df.explode("job_skill_set")

In [18]:
career_skill_mapping = career_skill_mapping.rename(
    columns={"job_skill_set": "Skill"}
)

In [19]:
career_skill_mapping = career_skill_mapping[
    ["category", "job_title", "Skill"]
]

In [20]:
career_skill_mapping.head(10)

  category                     job_title                             Skill
0       HR  Sr Human Resource Generalist                Employee Relations
0       HR  Sr Human Resource Generalist                Talent Acquisition
0       HR  Sr Human Resource Generalist            Performance Management
0       HR  Sr Human Resource Generalist         Compensation And Benefits
0       HR  Sr Human Resource Generalist   Employment Laws And Regulations
0       HR  Sr Human Resource Generalist                 Analytical Skills
0       HR  Sr Human Resource Generalist  Employee Benefits Administration
0       HR  Sr Human Resource Generalist        Hr Policies And Procedures
0       HR  Sr Human Resource Generalist            Recruitment Strategies
0       HR  Sr Human Resource Generalist                              Fmla

In [21]:
career_skill_mapping.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20833 entries, 0 to 1166
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   category   20833 non-null  object
 1   job_title  20833 non-null  object
 2   Skill      20833 non-null  object
dtypes: object(3)
memory usage: 651.0+ KB

In [22]:
career_skill_mapping.isnull().sum()

category     0
job_title    0
Skill        0
dtype: int64

In [23]:
career_skill_mapping.to_csv(
    "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_skill_mapping.csv",
    index=False
)

print("Career-Skill mapping saved successfully!")

Career-Skill mapping saved successfully!

In [24]:
career_profiles = df.groupby(
    ["category", "job_title", "job_description"],
    as_index=False
).agg({
    "job_skill_set": "first"
})

In [25]:
career_profiles["num_skills"] = career_profiles["job_skill_set"].apply(len)

In [26]:
career_profiles.head()

,category,job_title,job_description,job_skill_set,num_skills
0,Business Development,100% Remote | Business Development Manager - B...,JOIN THE LEOSOLVE GROUP AND DRIVE GLOBAL BUSIN...,"[B2B Sales, Negotiation, Communication, Client...",10
1,Business Development,"Account Executive, New Business Development, H...","ACCOUNT EXECUTIVE, NEW BUSINESS DEVELOPMENT, H...","[Sales Performance Tracking, Presentation Skil...",19
2,Business Development,Area Director Business Development,SUNRISE SENIOR LIVING WAS AGAIN CERTIFIED AS A...,"[Business Development, Account Management, Sal...",20
3,Business Development,"Associate, Corporate Business Development","COMPANY DESCRIPTION AT SERVICENOW, OUR TECHNOL...","[Market Research, Analytical Skills, Negotiati...",16
4,Business Development,Business Development,QUANTUM PAIN AND ORTHOPEDICS IS A PREMIER OUTP...,"[Microsoft Office Suite, Marketing, Data Analy...",14

In [27]:
career_profiles.isnull().sum()

category           0
job_title          0
job_description    0
job_skill_set      0
num_skills         0
dtype: int64

In [28]:
career_profiles.to_csv(
    "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_profiles.csv",
    index=False
)

In [29]:
career_profiles.to_json(
    "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_profiles.json",
    orient="records",
    indent=4
)

In [30]:
career_profiles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1167 entries, 0 to 1166
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   category         1167 non-null   object
 1   job_title        1167 non-null   object
 2   job_description  1167 non-null   object
 3   job_skill_set    1167 non-null   object
 4   num_skills       1167 non-null   int64
dtypes: int64(1), object(4)
memory usage: 45.7+ KB

In [31]:
career_profiles.shape

(1167, 5)

In [32]:
category_career_mapping = (
    df.groupby("category")["job_title"]
      .apply(lambda x: sorted(x.unique().tolist()))
      .reset_index()
)

category_career_mapping.rename(
    columns={"job_title": "careers"},
    inplace=True
)

In [33]:
category_career_mapping

                 category                                            careers
0    Business Development  [100% Remote | Business Development Manager - ...
1                 Finance  [2024 Finance Summer Internship, AVP Financial...
2                      HR  [AOC Human Resources Project Manager, Administ...
3  Information Technology  [2024 Summer - Information Technology (IT) Int...
4                   Sales  [Account Director - Leisure Sales (Miami or Ne...

In [34]:
category_career_mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  5 non-null      object
 1   careers   5 non-null      object
dtypes: object(2)
memory usage: 212.0+ bytes

In [35]:
category_career_mapping["num_careers"] = category_career_mapping["careers"].apply(len)

category_career_mapping

,category,careers,num_careers
0,Business Development,[100% Remote | Business Development Manager - ...,127
1,Finance,"[2024 Finance Summer Internship, AVP Financial...",192
2,HR,"[AOC Human Resources Project Manager, Administ...",89
3,Information Technology,[2024 Summer - Information Technology (IT) Int...,130
4,Sales,[Account Director - Leisure Sales (Miami or Ne...,182

In [36]:
category_career_mapping.to_csv(
    "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/category_career_mapping.csv",
    index=False
)

In [37]:
category_career_mapping.to_json(
    "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/category_career_mapping.json",
    orient="records",
    indent=4
)

In [38]:
from collections import Counter

In [39]:
# Count frequency of each skill
skill_frequency = Counter(all_skills)

print("Total Unique Skills:", len(skill_frequency))

Total Unique Skills: 4984

In [40]:
skill_frequency_df = pd.DataFrame(
    skill_frequency.items(),
    columns=["Skill", "Frequency"]
)

In [41]:
skill_frequency_df = skill_frequency_df.sort_values(
    by="Frequency",
    ascending=False
).reset_index(drop=True)

In [42]:
skill_frequency_df.head(20)

                    Skill  Frequency
0           Communication       1092
1         Problem Solving        878
2            Adaptability        588
3                Teamwork        569
4           Collaboration        341
5              Leadership        325
6         Time Management        316
7    Interpersonal Skills        288
8        Customer Service        272
9   Relationship Building        267
10    Attention To Detail        253
11          Data Analysis        251
12     Project Management        234
13  Organizational Skills        231
14            Negotiation        157
15                  Sales        148
16    Presentation Skills        144
17   Business Development        137
18     Financial Analysis        131
19     Strategic Thinking        127

In [43]:
skill_frequency_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4984 entries, 0 to 4983
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Skill      4984 non-null   object
 1   Frequency  4984 non-null   int64
dtypes: int64(1), object(1)
memory usage: 78.0+ KB

In [44]:
skill_frequency_df.isnull().sum()

Skill        0
Frequency    0
dtype: int64

In [45]:
skill_frequency_df.to_csv(
    "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/skill_frequency.csv",
    index=False
)

print("Skill frequency dataset saved successfully!")

Skill frequency dataset saved successfully!

In [46]:
career_statistics = career_profiles.copy()

career_statistics["description_length"] = career_statistics["job_description"].apply(len)

In [47]:
posting_count = (
    df.groupby("job_title")
      .size()
      .reset_index(name="posting_count")
)

In [48]:
career_statistics = career_statistics.merge(
    posting_count,
    on="job_title",
    how="left"
)

In [49]:
career_statistics = career_statistics[
    [
        "category",
        "job_title",
        "num_skills",
        "description_length",
        "posting_count"
    ]
]

In [50]:
career_statistics.head()

,category,job_title,num_skills,description_length,posting_count
0,Business Development,100% Remote | Business Development Manager - B...,10,2213,1
1,Business Development,"Account Executive, New Business Development, H...",19,3421,1
2,Business Development,Area Director Business Development,20,8957,1
3,Business Development,"Associate, Corporate Business Development",16,7501,1
4,Business Development,Business Development,14,3092,1

In [51]:
career_statistics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1167 entries, 0 to 1166
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   category            1167 non-null   object
 1   job_title           1167 non-null   object
 2   num_skills          1167 non-null   int64
 3   description_length  1167 non-null   int64
 4   posting_count       1167 non-null   int64
dtypes: int64(3), object(2)
memory usage: 45.7+ KB

In [52]:
career_statistics.isnull().sum()

category              0
job_title             0
num_skills            0
description_length    0
posting_count         0
dtype: int64

In [53]:
career_statistics.to_csv(
    "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_statistics.csv",
    index=False
)

print("Career statistics saved successfully!")

Career statistics saved successfully!

In [54]:
career_knowledge_base = career_profiles.merge(
    career_statistics[
        ["job_title", "description_length", "posting_count"]
    ],
    on="job_title",
    how="left"
)

In [55]:
career_knowledge_base = career_knowledge_base.rename(
    columns={
        "job_skill_set": "skills"
    }
)

In [56]:
career_knowledge_base = career_knowledge_base[
    [
        "category",
        "job_title",
        "job_description",
        "skills",
        "num_skills",
        "description_length",
        "posting_count"
    ]
]

In [57]:
career_knowledge_base.head()

,category,job_title,job_description,skills,num_skills,description_length,posting_count
0,Business Development,100% Remote | Business Development Manager - B...,JOIN THE LEOSOLVE GROUP AND DRIVE GLOBAL BUSIN...,"[B2B Sales, Negotiation, Communication, Client...",10,2213,1
1,Business Development,"Account Executive, New Business Development, H...","ACCOUNT EXECUTIVE, NEW BUSINESS DEVELOPMENT, H...","[Sales Performance Tracking, Presentation Skil...",19,3421,1
2,Business Development,Area Director Business Development,SUNRISE SENIOR LIVING WAS AGAIN CERTIFIED AS A...,"[Business Development, Account Management, Sal...",20,8957,1
3,Business Development,"Associate, Corporate Business Development","COMPANY DESCRIPTION AT SERVICENOW, OUR TECHNOL...","[Market Research, Analytical Skills, Negotiati...",16,7501,1
4,Business Development,Business Development,QUANTUM PAIN AND ORTHOPEDICS IS A PREMIER OUTP...,"[Microsoft Office Suite, Marketing, Data Analy...",14,3092,1

In [58]:
career_knowledge_base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9147 entries, 0 to 9146
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   category            9147 non-null   object
 1   job_title           9147 non-null   object
 2   job_description     9147 non-null   object
 3   skills              9147 non-null   object
 4   num_skills          9147 non-null   int64
 5   description_length  9147 non-null   int64
 6   posting_count       9147 non-null   int64
dtypes: int64(3), object(4)
memory usage: 500.4+ KB

In [59]:
career_knowledge_base.isnull().sum()

category              0
job_title             0
job_description       0
skills                0
num_skills            0
description_length    0
posting_count         0
dtype: int64

In [60]:
career_knowledge_base.to_csv(
    "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_knowledge_base.csv",
    index=False
)

In [61]:
career_knowledge_base.to_json(
    "/content/drive/MyDrive/AI POWERED PERSONALISED LEARNING PATH GENERATOR/Dataset/Processed/career_knowledge_base.json",
    orient="records",
    indent=4
)