In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
df = pd.read_csv("/content/archive (3).zip")

In [ ]:
df.head()

,job_id,category,job_title,job_description,job_skill_set
0,3902668440,HR,Sr Human Resource Generalist,SUMMARY\nTHE SR. HR GENERALIST PROVIDES HR EXP...,"['employee relations', 'talent acquisition', '..."
1,3905823748,HR,Human Resources Manager,BE PART OF A STELLAR TEAM AT YSB AS THE MANAGE...,"['Talent Acquisition', 'Employee Performance M..."
2,3905854799,HR,Director of Human Resources,OUR CLIENT IS A THRIVING ORGANIZATION OFFERING...,"['Human Resources Management', 'Recruitment', ..."
3,3905834061,HR,Chief Human Resources Officer,JOB TITLE: CHIEF HUMAN RESOURCES OFFICER (CHRO...,"['talent management', 'organizational developm..."
4,3906250451,HR,Human Resources Generalist (Hybrid Role),DESCRIPTION\n\n WHO WE ARE \n\nAVI-SPL IS A DI...,"['Microsoft Office', 'Data analysis', 'Employe..."

In [ ]:
df.drop(columns=["job_id"], inplace=True)

In [ ]:
df.drop(columns=["job_id", "skill_id"], inplace=True, errors='ignore')

In [ ]:
df.shape

(1167, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1167 entries, 0 to 1166
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   category         1167 non-null   object
 1   job_title        1167 non-null   object
 2   job_description  1167 non-null   object
 3   job_skill_set    1167 non-null   object
dtypes: object(4)
memory usage: 36.6+ KB

In [ ]:
df.columns

Index(['category', 'job_title', 'job_description', 'job_skill_set'], dtype='object')

In [ ]:
df.isnull().sum()

category           0
job_title          0
job_description    0
job_skill_set      0
dtype: int64

In [ ]:
df.fillna("Unknown", inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

In [ ]:
text_columns = df.select_dtypes(include='object').columns

for col in text_columns:
    df[col] = df[col].str.lower()

In [ ]:
for col in text_columns:
    df[col] = df[col].str.strip()

In [ ]:
for col in text_columns:
    df[col] = df[col].str.replace(r'[^a-zA-Z0-9, ]', '', regex=True)

In [ ]:
skill_mapping = {
    "ml": "machine learning",
    "ai": "artificial intelligence",
    "js": "javascript",
    "py": "python"
}

df.replace(skill_mapping, inplace=True)

In [ ]:
df.head()

,category,job_title,job_description,job_skill_set
0,hr,sr human resource generalist,summarythe sr hr generalist provides hr expert...,"employee relations, talent acquisition, perfor..."
1,hr,human resources manager,be part of a stellar team at ysb as the manage...,"talent acquisition, employee performance manag..."
2,hr,director of human resources,our client is a thriving organization offering...,"human resources management, recruitment, emplo..."
3,hr,chief human resources officer,job title chief human resources officer chroin...,"talent management, organizational development,..."
4,hr,human resources generalist hybrid role,description who we are avispl is a digital ena...,"microsoft office, data analysis, employee onbo..."

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1167 entries, 0 to 1166
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   category         1167 non-null   object
 1   job_title        1167 non-null   object
 2   job_description  1167 non-null   object
 3   job_skill_set    1167 non-null   object
dtypes: object(4)
memory usage: 36.6+ KB

In [ ]:
df.isnull().sum()

category           0
job_title          0
job_description    0
job_skill_set      0
dtype: int64

In [ ]:
df.to_csv("core_knowledge_preprocessed.csv", index=False)